### ISSUE TITLE
Parameterization stage

### ISSUE THREAD

**Issue by mhluongo** [keep-network/tbtc#116]
Originally discussed around [lot size](https://github.com/keep-network/tbtc/issues/3#issuecomment-482248449).

We have a number of economic and security parameters that we've left floating until we have proper simulations or rationale.

- ~~The [standard lot size](https://github.com/keep-network/tbtc/issues/3). We've talked about 0.1 to 1 BTC. 1 BTC has the most momentum but the question deserves settling before mainnet.~~ -> **there are now multiple governable lot sizes; see #415**
- [x] `m` and `n` for threshold wallets. These parameters are [core to fund security](https://github.com/keep-network/tbtc/issues/4) and the cost of acting as a signer. -> **this will be 3 of 3**

**Comment by Shadowfiend** [comment]
We're all done here. Updated the description with final changes and closing.
