### ISSUE TITLE
More realistic Compound v2 deployment on testnet

### ISSUE THREAD

**Issue by mhluongo** [keep-network/tbtc#130]
In #105, we agreed to stub out Uniswap behavior for development purposes. #117 suggests we'll have a similar solution for Compound in the short term.

Before mainnet, we should switch out the stubs for actual Compound contracts.

**Comment by Shadowfiend** [comment]
Closing this as there's no approach here, we're not deploying any Compound contracts currently (stub or otherwise), and this is about deployment of in use contracts. Some form of this may come back as #117 plays out post-mainnet, though #270 at least covers how we would link to it.
