### ISSUE TITLE
Internal audit of all external contracts

### ISSUE THREAD

**Issue by mhluongo** [keep-network/tbtc#131]
Before we go to audit, let's review all external contract usage. In particular,

- ~~Uniswap for on-chain liquidation (#105)~~ -> Uniswap has been removed.
- ~~Compound for optional signing bond leverage (#117)~~ -> Compound was never added.
- ~~Uniswap might also be used as an on-chain price data point (#114)~~

**Comment by Shadowfiend** [comment]
Nothing left here, closing.
