### ISSUE TITLE
V1 upgradeability path for tBTC

### ISSUE THREAD

**Issue by pdyraga** [keep-network/tbtc#139]
Figure out how upgrades are going to work in tBTC for the first version and externalize it into some document (RFC?)

**Comment by mhluongo** [comment]
We've opted for an even more extreme version, removing all "kill switches". *Caveat emptor* folks

**Comment by mhluongo** [comment]
Details on the slim governance surface area that has been included can be found [here](https://github.com/keep-network/tbtc/issues/406)
