### ISSUE TITLE
bitcoin-spv usage: compile in, link, or mix?

### ISSUE THREAD

**Issue by prestwich** [keep-network/tbtc#225]
carrying over from here: https://github.com/summa-tx/bitcoin-spv/pull/21#discussion_r308576608

in `bitcoin-spv@1.0.0` we required `DELEGATECALL` access to the library. As of v2.0.0 we will support both delegate and compiling library methods in (see the v2.0.0 README for usage). We can also mix access methods.

For eah use of `ValidationSPV`, `BytesLib`, etc, we should consider whether we would rather link (incurring >700 gas expense for the call) or compile in (incurring extra expense at deploy-time).

**Comment by mhluongo** [comment]
@NicholasDotSol confirming we're compiling in here so we can close

**Comment by Shadowfiend** [comment]
We are compiling in, and a switch to library won't land for v1. I'm going to fire up a separate issue to track looking at switching for v2.

**Comment by Shadowfiend** [comment]
Jk, I got my sides of the conversation mixed, we landed on taking the deployment hit. No new issue for now, I think everyone was on the same page.
