### ISSUE TITLE
low-level call for outside integrations

### ISSUE THREAD

**Issue by prestwich** [keep-network/tbtc#248]
Use `.call` for calling external contracts so that we can handle remote revert

**Comment by Shadowfiend** [comment]
I believe we're good here:
- We no longer special-case Uniswap; that is left for outside implementors.
- The price feed is checked for activity with `peek` (which returns a boolean) before `read` is called (which risks a revert).
- The relay interaction is limited to `getCurrentEpochDifficulty` and `getPrevEpochDifficulty`, which in the version we are referencing is a simple state read, so does not risk an unwarranted `revert`.

There is potential danger for revert with some calls to Keep, but these are fairly integral to the flow (e.g. `seizeSignerBonds`, `openKeep`, `submitSignatureFraud`), so reverts probably aren't the wrong thing to do, and we only semi-consider them “external” for our purposes.
