### ISSUE TITLE
Integration with external libraries - discussion

### ISSUE THREAD

**Issue by pdyraga** [keep-network/tbtc#270]
In our code, we integrate with contracts from external repositories such as `bitcoin-spv`, `OpenZeppelin`,`keep-tecdsa`, and others. We also have a proposition of adding even more external dependencies (see https://github.com/keep-network/tbtc/pull/263). We need to discuss and establish a common approach for integrating those contracts with our code.

There are four approaches for integration contracts from an external repository we experimented with so far:
1. git submodule - we add an external repository as a git submodule and we can interact with the entire codebase
2. npm dependency - some libraries have `package.json` configured in a way allowing us to add them as a dependency to `node_modules`. We can then interact with their entire codebase
3. ethereum package manager - we experimented with this project but seems it's still in early days, and may not but sufficient for us
4. defining interface in our codebase containing only the functions we use and casting contract address to an interface
   ```
   interface ExternalSystem {
     function doWork()
   }
   address externalSystemAddress = ...
   ExternalSystem(externalSystemAddress).doWork()
   ```

The qualities of our choice we should measure against:
- clear separation of what is our code and what is an external code
- easiness of setting up a development environment
- gas cost of interacting with the code
- the cost of maintaining the dependency

### Proposition

There are two important differences between contracts from other repositories:
1. We use contracts as a library in our code (`bitcoin-spv`, `OpenZeppelin`)
2. We interact with an external system, deployed on the chain (`keep-tecdsa`)

Those two use cases require different approaches.

#### Library 
For the library, it seems that the `node_module` approach (approach number 2) should be the preferred one. Both `OpenZeppelin` and `bitcoin-spv` support it. We can then interact with the entire codebase - use various exported functions, modifiers, inherit from contracts and so forth. This is what we expect from a library.

#### External system
For the external system, I think we should interact using interface (approach number 4). 

Although it seems to be a common approach in solidity world to import entire codebase of the external system, it doesn't feel right.  Taking an example from other ecosystems, we don't import the source code of payment provider to our application, but instead, we use WSDL.

We can have one place (`external` directory?) where we can define interfaces to external systems as well as hardcode addresses of their contracts. This would look e.g.: 

```
external/Keep.sol
```

`Keep.sol`:
```
address keepVendorAddress = ...

interface KeepVendor {
  openKeep() address
}

interface Keep {
  sign(byte32 digest)
}
```

and later we use:
```
  address vendor = KeepVendor(keepVendorAddress);
  Keep keep = Keep(vendor.openKeep())
```

Ideally, such interfaces should be exposed by all external systems, without a need of embedding their entire code in our repo as git submodule or npm dependency. 

Worth noting, this discussion may influence how people will interact with `keep-tecdsa` or  random beacon.

**Comment by Shadowfiend** [comment]
I believe this is done and implemented now, as described in the tail end of the issue description. Closing.
