### ISSUE TITLE
ERC20 approveAndCall functionality

### ISSUE THREAD

**Issue by NicholasDotSol** [keep-network/tbtc#273]
Implement `approveAndCall` token functionality to avoid multiple transactions for calling `Deposit` functions that require prior `approval`

Implementer: @NicholasDotSol
Feature buddy: @liamzebedee

**Comment by Shadowfiend** [comment]
@NicholasDotSol If I'm not mistaken this is implemented now since we have `FundingScript` and `RedemptionScript`, no?

**Comment by Shadowfiend** [comment]
^^ the answer is yes.
