### ISSUE TITLE
ERC20 ERC721 and further ACL

### ISSUE THREAD

**Issue by NicholasDotSol** [keep-network/tbtc#278]
ERC20

- `Minter roles` and `minter authority` was used interchangeably.  `Minter Rolle` were defined and enforced via `ACL` in #253.

ERC721

- `Minter roles` are self-defined as `721` Tokens are minted by the `Factory` and should not be minted elsewhere. We need to enforce this with `ACL`. #271 is a draft for this.

Further

- ACL should not be totally `close-circuit` to allow for upgradability in the future. `ACL` `addresses` should be modifiable. #271 implements 2 files for `MinterAuthority`. One for `721` and one for `ERC20`. Depending on our approach these should allow addition of upgradability logic

**Comment by Shadowfiend** [comment]
This was completed; note that full upgradeability is now undesired, so the final ACL approach was a bit different. ACL was more or less finalized in #420.
