### ISSUE TITLE
Support for legacy and witness deposit transaction

### ISSUE THREAD

**Issue by NicholasDotSol** [keep-network/tbtc#309]
`bitcoin-spv2.0` allows support of full legacy and witness transactions for deposit as compared to only witness currently.

- [ ] Ensure that both witness and legacy transactions are supported in `Deposit`

This Issue should be taken care of after Deposit is in a stable and testable state. Work involves testing the contract thoroughly with the goal of finding cases where legacy transactions don't work. There is a possibility no such cases can be found.

**Comment by mhluongo** [comment]
@NicholasDotSol I believe we support both tx types, and are limits are around tx input size / total tx size. Can you confirm and close this out, or retitle the issue?

**Comment by NicholasDotSol** [comment]
👍 closing
