### ISSUE TITLE
Test liquidation flows

### ISSUE THREAD

**Issue by liamzebedee** [keep-network/tbtc#319]
Liquidation flows located in `startSignerAbortLiquidation` (timeouts) and `startSignerFraudLiquidation` (stolen bonds/tbtc) are not thoroughly tested yet. 

Right now we have two types of liquidation - (1) auction and (2) on-chain using Uniswap. The liquidation flows should test that ETH/TBTC is properly refunded to the relevant actors in the system. 

We must also consider whether the liquidation comes from non-redemption (usual operation) or redemption (redeeming tbtc for btc). It may be wise to refactor some code in DepositLiquidation to make this simpler.
 
I previously implemented [some code](https://github.com/keep-network/tbtc/blob/test-liquidation-flows/implementation/test/DepositLiquidationTest.js#L686) for testing onchain liquidation, which might be helpful.

**Comment by Shadowfiend** [comment]
These are generally taken care of at this point, both with state tests and with targeted tests @NicholasDotSol wrote.
