### ISSUE TITLE
Sync liquidation protocol with spec

### ISSUE THREAD

**Issue by liamzebedee** [keep-network/tbtc#325]
There are some aspects of the liquidation code right now that are out-of-sync / need a bit of discussion. These are:

 * signer fees are currently reserved at time of minting TBTC. We don't require them to be paid in redemption anymore.
 * let's not burn ETH in liquidation flows. Instead, send it to a maintainer (if possible). https://github.com/keep-network/tbtc/issues/105#issuecomment-511631608
 * UX-wise, if redemption fails, it might be better to refund TBTC to the user rather than the signer bonds. https://github.com/keep-network/tbtc/issues/105#issuecomment-510184994
 * consider slippage when liquidating with Uniswap (ie. if it can buy up enough TBTC) https://github.com/keep-network/tbtc/issues/105#issuecomment-500242077

**Comment by mhluongo** [comment]
✅
