### ISSUE TITLE
Price feed v1 finalization

### ISSUE THREAD

**Issue by Shadowfiend** [keep-network/tbtc#336]
Also involves:
- Investigating API of Maker's medianizer, which we'll be using for this, and any testing concerns around it.

High-level estimate: S

Breakdown: @liamzebedee 
* Create medianizer external repo. **4pt**

  * Medianizer is probably best deployed as an external, rather than imported as a library.

    * They use Dappsys tooling, as opposed to Truffle. As it stands, it is not built to the NPM/OpenZeppelin standard of importing Solidity libraries.

      ie. `import {Contract} from "package/src/Contract.sol"`, where node_modules/package/src/Contract.sol exists

    * Medianizer library has a tree of dependencies (depth 3, total 8) which would also need to be imported. They depend on each other. 

  * Our external deployment approach is discussed here https://github.com/keep-network/tbtc/issues/270. 

    * Base the design off of keep-network/uniswap

* Deploy medianizer external to Keep testnet. **2pts**

  * Liase with Sloan here

* Design Medianizer ACL integration with TBTCSystem. **1pt**

* Integrate medianizer external into tBTC deployment.

  * Solidity interface. **1pt**
  * Integration test. **1pt**

    * Relatively simple - `set(address)` to update from an operator, `poke()` to compute and emit the new medianized value, `read()` to read the cached value

* Remove old PriceFeedV1. **1pt**

Total: *10pts*

**Comment by mhluongo** [comment]
Done and done!
