### ISSUE TITLE
Random beacon integration

### ISSUE THREAD

**Issue by Shadowfiend** [keep-network/tbtc#337]
The work for choosing signers from the beacon results lives in #335. This is solely about switching out our current stub random generation with the beacon.

Also involves:
- Managing payment for beacon entry.
- Callback registration with the beacon.

High-level estimate: M

Breakdown: @NicholasDotSol 
- Integrate Random beacon and reach a callable state: 4
  Exposed view function that allows access to the beacon result.
- Use random beacon (economics incomplete initial implementation): 4
  Beacon is hooked up instead of stub randomness. -> *may need some extra support from the beacon team.*
- Implement required pricing logic: 8

Optimistic total: 16pt

**Comment by mhluongo** [comment]
Would we call this done? @nkuba

**Comment by nkuba** [comment]
Yes, this is covered. Let's close this issue.
