### ISSUE TITLE
Liquidation remaining implementation

### ISSUE THREAD

**Issue by Shadowfiend** [keep-network/tbtc#340]
High-level estimate: S-M

Breakdown: @liamzebedee 
* Iterate on liquidation design/doc. 4
  * Detail the various actors and amounts they receive, in clear terms. 
  * A diagram might be appropriate for conveying this.
  * Close leftover discussions on protocol from https://github.com/keep-network/tbtc/issues/325, https://github.com/keep-network/tbtc/issues/332

* Test startSignerAbortLiquidation and startSignerFraudLiquidation flows. 16
  * This area would be better estimable with a clear design from issue 1 first. See https://github.com/keep-network/tbtc/issues/319 for some previous work on this.
  * Redemption
  * Non-redemption
  * Auction liquidation
  * Uniswap liquidation

**Comment by mhluongo** [comment]
Done and done.
