### ISSUE TITLE
Remove signerFee minting from Vending Machine Deposit qualification

### ISSUE THREAD

**Issue by NicholasDotSol** [keep-network/tbtc#376]
Removing the signerFee minting from Vending also removes VendingMachine call restriction on qualifyDeposit. Instead the qualification can be done directly via `DepositFunding #provideBTCFundingProof`. To compensate Signer fees should be awarded on redemption. 

- [x] Remove SignerFee mint from qualifyDeposit
- [x] update `qualifyDeposit` to function as a `unqualified Deposit -> TBTC` wrapper. 
- [x] Update internal TBTC minting functions to mint full lostSize
- [x] Clarify updated `TBTC` redemption requirements in [redemption PR](https://github.com/keep-network/tbtc/pull/374)
- [x] fix tests

epic: https://github.com/keep-network/tbtc/issues/334

**Comment by Shadowfiend** [comment]
This was completed but got missed.

Notably the final approach here was to have an `unqualifiedTdtToTbtc` function on the `VendingMachine` allowing a direct line from a TDT without proof to minted TBTC (minus escrowed signer fee). The funding script is still used to remove the additional need to approve the TDT transfer in a separate transaction.
