### ISSUE TITLE
seizeSignerBonds() re-call revert

### ISSUE THREAD

**Issue by NicholasDotSol** [keep-network/tbtc#379]
Working from a flow here `seizeSignerBonds` has been called and funds have not ben returned, any other function that calls `seizeSignerBonds` will revert with `No funds received, unexpected` due to before-after balance check.

Example flow:
`provideFundingECDSAFraudProof` where the funding timeout has not elapsed ->
`seizeSignerBonds` called and state changed to `FraudAwaitingBTCFundingProof`.
wait for funding fraud timeout  -> `notifyFraudFundingTimeout()` calls `partiallySlashForFraudInFunding` -> which calls `seizeSignerBonds()` - revert

**Comment by Shadowfiend** [comment]
This is no longer an issue (I just double-checked the paths to make sure :grin:).
