### ISSUE TITLE
Document fee rebates.

### ISSUE THREAD

**Issue by liamzebedee** [keep-network/tbtc#389]
There's been some confusion around the signer fee, fee rebate token (*previously* beneficiary reward), and the mechanics of the signer fee rebate. I'm writing this all down for future reference.

### Paying the signer fees
We have to pay signers for their services, hence the signer fee. However, when do we demand payment and from whom? There are a couple options:

 1) paid at redemption
 2) paid upfront, as part of the Bitcoin transaction
 3) paid upfront, during funding on Ethereum

We could naively demand payment at redemption, but if a deposit is closed, it is unreasonable to take the fee from the signer's bonds. The second option of including the signer fee during the Bitcoin funding tx works, but adds additional cost for depositors, and is more inflexible than Ethereum. The last option is taking the signer fee out of the deposit amount, during the funding event on Ethereum.   

So we escrow the signer fee of 0.005 TBTC upfront during funding. During deposit redemption, the redeemer pays the 1 TBTC + 0.005 TBTC, which pays the original depositor for their escrowed signer fee, and thereafter the signers. 

### Reducing friction for depositors
Now, the depositor is paid on redemption, but that locks up 0.005 of **their** TBTC for the duration of the deposit's lifetime. The signers are paid the full 0.005 TBTC at redemption, but the capital is otherwise underutilised until then. 

To make this capital productive, we can mint a token which trades as a coupon for the to-be-paid escrowed signer fee - the **fee rebate token** (FRT). At redemption, the fee is thereby paid to whomever holds the FRT.

### Reducing friction at redemption
*Intuition*. If the original depositor then goes after to redeem their deposit, it would not make sense to charge them for signer fees, since they've already escrowed them. 

We rebate the signing fees in exchange for an FRT. When redemption is finalised, we send the fee rebate unless the deposit has the FRT.

*Intuition*. Deposits have fixed term lengths, and when they aren't redeemed, they incur auction costs for signers (auction currently scales from 90% to 100% of their bonds). We should incentivise older deposits being closed.

The FRT holder is not rebated if the deposit becomes at term. This incentivises the FRT holders to redeem deposits before they expire or sell their FRT to someone who will.

**Comment by Shadowfiend** [comment]
The system incentivizes closing of older deposits (by not charging the signer fee to the redeemer), but that happens irrespective of the FRT's existence---even if there is no FRT, redeeming an at-term deposit by anyone other than the TDT holder costs 1 TBTC, with the fee taken from the TDT holder's repayment for redemption. 

The FRT's only real purpose is to give the original TDT holder an opportunity to get their escrowed fee back if there's demand for the deposit prior to term. The spec says:

> This token grants the right to a fee rebate if and when the pre-term deposit is redeemed by another party.

I think that sufficiently describes the mechanism.

Closing this issue for now---if we have further details we want to flag about the FRT, let's capture them elsewhere.
