### ISSUE TITLE
Distribute remaining ETH TBTC

### ISSUE THREAD

**Issue by NicholasDotSol** [keep-network/tbtc#392]
There could be remaining ETH/TBTC in Deposit, it shouldn't happen as part of the regular flow, but might occur as part of user error. 
We can add a withdrawal function accessible after the contract halts.

**Comment by mhluongo** [comment]
Have we addressed, or is it WONTFIX for rc.1 @Shadowfiend @NicholasDotSol?

**Comment by Shadowfiend** [comment]
#704 addresses the leftover TBTC issue. I'll need to check on ETH.

**Comment by mhluongo** [comment]
Closing the ETH bit as WONTFIX for v1

**Comment by Shadowfiend** [comment]
v1 WONTFIXes that we want to address in the future I've been dropping in the post-mainnet milestone, fwiw.

**Comment by Shadowfiend** [comment]
(And leaving open.)
