### ISSUE TITLE
TECDSA Keep is never closed

### ISSUE THREAD

**Issue by NicholasDotSol** [keep-network/tbtc#491]
At the end of the TBTC deposit lifecycle happy path, the deposit is supposed to close the keep in order to release the signer bonds. However, there is no call to `closeKeep`

- [ ] Close the keep releasing the signer bonds.

**Comment by pdyraga** [comment]
This one is already logged in https://github.com/keep-network/tbtc/issues/473 and addressed in https://github.com/keep-network/tbtc/pull/490

**Comment by NicholasDotSol** [comment]
ah yes. Closing
