### ISSUE TITLE
Funder loses payment if Keep creation fails

### ISSUE THREAD

**Issue by NicholasDotSol** [keep-network/tbtc#495]
If a signing group fails to be established, payment for the keep is not returned even though one could assume that the signing group tried to play unfairly. The signing group might intentionally try to cause this scenario to interfere with the system.

- [ ] ensure that a keep group is always established or otherwise the funder is refunded the fee for the keep

refs: #495 
additional refs: #494

**Comment by pdyraga** [comment]
One possible option is to seize signer bonds after the timeout, return payment to the customer from seized bonds and then return partial signer bonds to signers.

**Comment by NicholasDotSol** [comment]
@pdyraga If the keep creation fails we should get a TX revert.
What might fails is the signer setup and return of the pub key. 
At any time after `createNewKeep` is called we can seise Signer bonds, right?

**Comment by pdyraga** [comment]
> @pdyraga If the keep creation fails we should get a TX revert.

Yes, this is how it works.

> What might fails is the signer setup and return of the pub key.

Yes, key is submitted once generated and [there is a fixed timeout for that](https://github.com/keep-network/keep-tecdsa/blob/v0.9.0/solidity/contracts/BondedECDSAKeep.sol#L48)

> At any time after `createNewKeep` is called we can seise Signer bonds, right?

Yes. Any time after creating new keep and before closing it or seizing bonds (seizing bonds closes keep).
