### ISSUE TITLE
Deposit state transition front-running

### ISSUE THREAD

**Issue by NicholasDotSol** [keep-network/tbtc#498]
An entity that can provide proof for fraudulent ECDSA signatures or SPV proofs in the liquidation flow is rewarded with part of the deposit contract ETH value.
However, the methods under which proof is provided are not protected from front-running allowing anyone to observe transactions to provideECDSAFraudProof/ provideSPVFraudProof and submit the same proofs with providing a higher gas value.

- [ ] implement a commit/reveal scheme to lock in proof in one block, and reveal the details in another.

**Comment by Shadowfiend** [comment]
Gut reaction here was that we're comfortable with this tradeoff, at least for v1, but need to mull it further and haven't gotten to it yet.

**Comment by NicholasDotSol** [comment]
>  we're comfortable with this tradeoff

Agree here

**Comment by Shadowfiend** [comment]
The note I sent to the auditors for the audit on this one:

> In general, we are comfortable with front-runnable interactions that ensure system integrity, as long as such front-running does not remove the original incentive of the submitter. We believe remaining front-runnable interactions have clear benefits to system actors, such that even if they are front-run, they have reason to submit the transaction.

Closing!
