### ISSUE TITLE
Funding/redemption script revert error string may be malformed

### ISSUE THREAD

**Issue by NicholasDotSol** [keep-network/tbtc#509]
On a high-level revert, `returnData` will already include the typical “error selector”. As the scripts propagate this error message, it will add another error selector, which may make it difficult to read the error message.

- [ ] Ensure nested error selectors are handled in external libraries, rather than adding an assembly-level revert to the affected contracts.

**Comment by liamzebedee** [comment]
Some more reference on how the `returnData` for revert is structured -

> The provided string is abi-encoded as if it were a call to a function Error(string). In the above example, revert("Not enough Ether provided."); returns the following hexadecimal as error return data:

> 0x08c379a0                                                         // Function selector for Error(string)
0x0000000000000000000000000000000000000000000000000000000000000020 // Data offset
0x000000000000000000000000000000000000000000000000000000000000001a // String length
0x4e6f7420656e6f7567682045746865722070726f76696465642e000000000000 // String data

https://solidity.readthedocs.io/en/latest/control-structures.html#error-handling-assert-require-revert-and-exceptions

**Comment by liamzebedee** [comment]
@Shadowfiend @NicholasDotSol I don't quite understand the auditor's concern re: adding an assembly-level revert to the affected contracts. Why don't we just slice off the Error function selector (see above) in Solidity?

**Comment by Shadowfiend** [comment]
I prefer this approach I think but never got a chance to poke at it.

**Comment by Shadowfiend** [comment]
I think the audit note was saying that rather than trying to revert from the contracts the scripts were calling in such a way that there would be no nested selector, we should handle the nested selector in the external library---in this case, the scripts---which is what we've chosen to do.
