### ISSUE TITLE
broken links from documentation

### ISSUE THREAD

**Issue by claveros** [keep-network/tbtc#549]
Most of the links from the documentation are broken:
https://docs.keep.network/tbtc/index.html

ie:
https://docs.keep.network/signer-fees/index.html 
instead of:
https://docs.keep.network/tbtc/signer-fees/index.html

**Comment by Shadowfiend** [comment]
Oh dear, well spotted. I'll have a look at our build and see where this is happening… Honestly I've been meaning to move these to live on `docs.tbtc.network`, so that may be the ultimate solution here.

Thanks for the report!
