### ISSUE TITLE
notifyCourtesyCall is altruistic and should be removed

### ISSUE THREAD

**Issue by wjmelements** [keep-network/tbtc#603]
If it is possible to liquidate an account, I should be able to liquidate it immediately. Any delay is a systematic risk because the price can move faster than your allowance.

A larger concern is that there is no reason a liquidator should notify when it can let a competitor spend that gas. Consider the strong congestion coinciding with a large price move. Competing transactions can pay their senders thousands of dollars. Why should I notifyCourtesyCall?

If nobody does notifyCourtesyCall, the account cannot be liquidated, and tBTC would become undercollateralized.

**Comment by mhluongo** [comment]
It's not. You can `notifyCourtesyCall` your own deposit to unlock the deposit for redemption, returning your bond. Signers want to call their own deposits to avoid liquidation

**Comment by mhluongo** [comment]
Nobody needs to call `notifyCourtesyCall` for liquidation. If a deposit is severely under-collateralized anyon can call for direct liquidation, and earn a few for doing ao

**Comment by wjmelements** [comment]
Thank you for clarifying.

I am skeptical that regular users will call themselves, but I am glad that I can still liquidate. It remains an issue that you use liquidationInitiated to determine the auctionValue and that initiation is altruistic. Hopefully the default ratio is sufficient incentive for your smallest accounts.

**Comment by Shadowfiend** [comment]
> It remains an issue that  […] initiation is altruistic.

Can you explain more of your thinking here? Why do you see initiation as altruistic?

**Comment by wjmelements** [comment]
> Why do you see initiation as altruistic?

For the case you aren't immediately liquidating, it helps your competitors at your own expense. There is no reward for initiation as far as I can tell, so nobody will do it unless they are planning to immediately liquidate.

**Comment by mhluongo** [comment]
> it helps your competitors at your own expense

One more comment here- a single economic entity might have 2 or even all 3 signers behind a particular wallet, meaning there's even more reason for this call. Closing as WONTFIX

**Comment by Shadowfiend** [comment]
Also of note: for collateralization liquidation, the initiator receives half of the amount left after the auction. For fraud, the initiator receives any leftover amount.
