### ISSUE TITLE
txOutputVector expected to have less than 252 elements but not enforced

### ISSUE THREAD

**Issue by sr-gi** [keep-network/tbtc#647]
`validateAndParseFundingSPVProof` expects to have a `_txOutputVector` with no more than 252 (0xFC) values, but this is not enforced by` _txOutputVector.validateVout()`.
https://github.com/keep-network/tbtc/blob/100e5aae60aad209b0d3c6d495438d2b5b270fd3/solidity/contracts/deposit/DepositUtils.sol#L190-L216

BTCUtils defines `_nOutputs` as a `uint256` (https://github.com/summa-tx/bitcoin-spv/blob/master/solidity/contracts/BTCUtils.sol#L487-L489).

Since `_fundingOutputIndex` is defined as a `uint8`, values over `255` will fail, however values 253-255 will be wrongly parsed, creating at least two issues with the current code.

## `findAndParseFundingOutput` will fail

`findAndParseFundingOutput` extracts the output that needs to be checked (`extractOutputAtIndex`). This extraction implies a `varint` parsing, that for output indexes `0xFD, 0xFE and 0xFF` will return a data length of `2, 4 and 8` respectively. Since the output passed is a single byte the function will [return an error](https://github.com/summa-tx/bitcoin-spv/blob/master/solidity/contracts/BTCUtils.sol#L54-L55) that will make [this require to fail](https://github.com/summa-tx/bitcoin-spv/blob/master/solidity/contracts/BTCUtils.sol#L343).

Given that `findAndParseFundingOutput` is called as part of `provideBTCFundingProof`, this will case funds to be potentially lost if the deposit is funded with an output in the 253th, 254th or 255th position (any other output further down will also fail, but this is expected given the `uint8` restriction of `_fundingOutputIndex`).

## `_utxoOutpoint` will be wrongly encoded

If we ignore the previous issue, the incorrect parsing of the `_fundingOutputIndex` would make the contract store an invalid `_utxoOutpoint` for the same value range:

```
value | expected | encoded 
0xFD  | 0xFDFD00 | 0xFD0000
0xFE  | 0xFDFE00 | 0xFE0000
0xFF  | 0xFDFF00 | 0xFF0000
```

This will cause the redemption of the funds to fail, since the output that will be [extracted and compared on redemption](https://github.com/summa-tx/bitcoin-spv/blob/master/solidity/contracts/BTCUtils.sol#L283-L288) will not match the one stored in the contract.

https://github.com/keep-network/tbtc/blob/100e5aae60aad209b0d3c6d495438d2b5b270fd3/solidity/contracts/deposit/DepositRedemption.sol#L345-L348

**Comment by sr-gi** [comment]
PS2: I guess UX-wise it'll be good to document the 252 max output index limitation (if it is not lifted), since I didn't realise about it from reading https://docs.keep.network/tbtc/.

This may cause some issues if creating the finding from a Wallet you have no complete control of, for instance an exchange that may batch redemptions into a transaction with many outputs.

**Comment by mhluongo** [comment]
> I guess UX-wise it'll be good to document the 252 max output index limitation (if it is not lifted),

Exactly- in the mainnet dApp we made "not funding from a wallet I don't control" a click-through. Even without this issue there, exchange batching can grow the size of a tx beyond what we can verify in a block

We'll make sure it's properly documented in #646

**Comment by sr-gi** [comment]
After carefully checking Summa's BTCUtils I found this has actually two issues that come from the fact that the `_txOutputVector` max value is not being enforced. 

I will update the initial to cover both.

**Comment by Shadowfiend** [comment]
To check my overall understanding here, the core issue is that currently it's impossible to provide funding proof for output indexes >252. 253-255 ultimately fail the `extractOutputAtIndex` require, so `provideBTCFundingProof` in that scenario will revert with `Read overrun during VarInt parsing`, while >255 will fail at encoding time.

Continuing down that, the bad UTXO endpoint encoding cannot happen in tBTC due to the above, though it would be nice if bitcoin-spv handled this for completeness.

Given that, is it fair to say that this is *solely* an issue for UX? Or is there a mitigation we need to implement in the contract that I missed?

**Comment by sr-gi** [comment]
> Given that, is it fair to say that this is _solely_ an issue for UX? Or is there a mitigation we need to implement in the contract that I missed?

Ideally, `_fundingOutputIndex` should be uint256 so funds could be deposit using any output. Practically, this seems to be an issue, since parsing hundreds of outputs may be non feasible. This may change with the [new approach](https://github.com/summa-tx/bitcoin-spv/blob/3a35db8480110970775abb8f6f89956f7872d35f/solidity/contracts/TypedMemView.sol) being currently implemented by @prestwich, but I guess he'll be best to asses that.

Until then, as long as you have a way to prevent the user from funding from a wallet he does not control (as @mhluongo was referring in an earlier message) or make sure the user is aware that funding from a high output index will involve lose of funds, it should be OK.

**Comment by Shadowfiend** [comment]
Yeah, the current implementation already maxes out the block gas limit before we hit 200 outputs, I believe (see [this analysis](https://docs.google.com/spreadsheets/d/1YgNNqx_bnN54yggX-X8OQbyCX6B1U-7TBcrqsGlxay0/edit#gid=0) of gas costs for on-chain SPV proofs that @NicholasDotSol did). Definitely hoping the memviews boost us past that for the next version, though I believe when we looked at Bitcoin transaction history that large-output-count transactions from exchanges could get *very* large indeed. Need to dig up some numbers from February.

**Comment by Shadowfiend** [comment]
Closing this in favor of #646, which is a placeholder for the UX warnings around this.
