### ISSUE TITLE
Naming utxoSize

### ISSUE THREAD

**Issue by sr-gi** [keep-network/tbtc#660]
This is completely subjective, so feel free to flag as wont-fix.

I would avoid referring to "size" when you are talking about value, since this can lead to some misconceptions that could end up leading to bugs.

I've seen this for `lotSizeSatoshis`, `lotSizeTbtc` and `utxoSize`, but it is specially relevant for the latter. Since a UTXO is a struct containing both a script and a value, the size is normally used to refer to the length in bytes of the struct, but not to the value hold by it.

**Comment by mhluongo** [comment]
"lot size" is a pretty deep nomenclature change, but `utxoSize` might be an easy fix. I'd also expect `utxoSize` to refer to the number of bytes in the struct.

Thoughts @Shadowfiend?

**Comment by Shadowfiend** [comment]
`utxoSize` -> `utxoValue`? Yeah, should be doable. Only snag will be making sure tbtc.js and other downstreams are ready for the change in event parameter name [for `RedemptionRequested`](https://github.com/keep-network/tbtc/blob/100e5aae60aad209b0d3c6d495438d2b5b270fd3/solidity/contracts/DepositLog.sol#L31). Agree this seems like a good move, and it's not like there's going to be a better time to do it later.
