### ISSUE TITLE
Expose funding UTXO info on Deposit

### ISSUE THREAD

**Issue by liamzebedee** [keep-network/tbtc#666]
Currently, extracting the funding UXTO information is cumbersome. Exposing this would be useful for building explorers etc. 

See [comment in tbtc.js for context](https://github.com/keep-network/tbtc.js/issues/33).

**Comment by mhluongo** [comment]
@liamzebedee want to propose a solution via PR? We don't have long to make dev experience improvements like this

**Comment by liamzebedee** [comment]
Ofc. It was only a bookmark, fwiw, but could've self-assigned for better clarity.
