### ISSUE TITLE
Incorrect doc of notifySignatureTimeout() and notifyRedemptionProofTimeout()

### ISSUE THREAD

**Issue by elishadrion** [keep-network/tbtc#678]
In `Deposit.sol`, as shown [here](https://github.com/keep-network/tbtc/blob/master/solidity/contracts/deposit/Deposit.sol#L241), it is stated that failure to provide a signature or a redemption proof consitutes fraud.

This is inconsistent with the eponymous functions of `DepositRedemption.sol`, as shown [here](https://github.com/keep-network/tbtc/blob/master/solidity/contracts/deposit/DepositRedemption.sol#L365), which calls `startLiquidation(false)`.

**Comment by Shadowfiend** [comment]
Yeppppp this was on my radar thank you :bow::bow::bow:

**Comment by Shadowfiend** [comment]
I'm doing a mega-branch with a fairly large cleanup of `Deposit.sol` from an API + docs perspective, captured in #695. Closing this issue in its favor; expect to see this early next week, though you can have a sneak peek at https://github.com/keep-network/tbtc/tree/notification-station .
