### ISSUE TITLE
Insufficient signer bonds to cover setup fee

### ISSUE THREAD

**Issue by k0kk0k** [keep-network/tbtc#711]
When i try to create a deposit (mint), the smart contract `TBTCSystem` returns the following error: 
```
execution reverted: Insufficient signer bonds to cover setup fee
0x08c379a00000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002c496e73756666696369656e74207369676e657220626f6e647320746f20636f766572207365747570206665650000000000000000000000000000000000ed4e00
```
transaction was sent from: `0x9c4d6bB6f874f3D522fc9f45034DFfB2dAF383be`

Possibly relation with issue: https://github.com/keep-network/keep-ecdsa/issues/504

**Comment by Shadowfiend** [comment]
Please see my detailed explanation on how we got there on Ropsten in the above issue.

To clarify, this is not a bug, just the system behaving as expected in the face of certain price changes.
