### ISSUE TITLE
tBTC spec table of content

### ISSUE THREAD

**Issue by nahuus123** [keep-network/tbtc#737]
Not sure if this was intentional or by mistake but the governance functions are in red in the table of contents.

![Screenshot_20200919-194045_Adobe Acrobat](https://user-images.githubusercontent.com/71384922/93685478-07301080-fab0-11ea-9d04-cb9388db4659.jpg)

**Comment by Shadowfiend** [comment]
This is the default styling for monospaced text in asciidoc's default rendering styles, and we haven't done any modifications there. We do have some plans in that dept but they're not immediately scheduled right now.
